complete phase 01
Star-Academy/Summer1403-SE-Team03 pull request #1
Opened 2024-07-20 16:22 UTC by mahdijafariii

we tried to make this exercise as least complexity as possible, and it took us some time to set the property and get the values ​​from Jason (the difference in setting the property that you linked to Discord) 
Overall it was good :)

2024-07-21 06:46 UTC, navidnasyry requested changes

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/.idea/.idea.ConsoleApp1/.idea/.gitignore
این پوشه چیهههههههههههه؟؟
باید رو گیت باشه؟؟

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.deps.json
این پوشه چیه؟ باید رو گیت باشه؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.dll
say hello to gitignore:)))))

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.runtimeconfig.json
same

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.exe
same

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.pdb
same

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Person.cs
> +    public int id { get; set; }
read about convention naming in c#

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +    public static void Main(string[] args)
تابع طولانیه:(

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +    public static void Main(string[] args)
چه کنیم؟ چطوری بشکنیمش؟

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        foreach (var pj in persons)
در باره پرفورمنس foreach بخونین:)

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +    }
خیلیییییییییی طولانیه تابع اصلی

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +    private static List<T> ReadFromJson<T>(string path)
منطقش رو کلاس بزنیم براش

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/ReadJson.cs
دو تا کلاس توی یه فایل؟

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/ReadJson.cs
درباره sealed بخونین توی c#

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/ReadJson.cs
> +    public int StudentNumber { get; set; }
why int??

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        foreach (var sj in scores) studentArr[sj.StudentNumber - 1].studentGrades.Add(sj.Lesson, sj.Score);
نامگذاری خوانا تر

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        foreach (var p in studentArr)
naming

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        // CW students
هیچ کامنتی در کد نباشد.. چرا؟؟؟؟؟؟؟؟؟؟

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        // Sort the array with linq
use summary instead of comment

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var persons =
use prettier

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +                @"database\scores.json");
اسم خاص فایل ها هارد کد باشه تو کد خوبه؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟

2024-07-21 06:46 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        for (var i = 0; i < 3; i++) Console.WriteLine(sortedStudent.ElementAt(i).ToString());
درباره formattingهایی که ToString میگیره بخونین؟ Culture-insensitive چیه؟ بخونین دربارش

2024-07-21 07:49 UTC, mahdijafariii commented on phase1/ConsoleApp1/.idea/.idea.ConsoleApp1/.idea/.gitignore
حل شد :)

2024-07-21 07:49 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.deps.json
حل شد :) 2

2024-07-21 07:49 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.dll
حل شد :) 3

2024-07-21 07:49 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.runtimeconfig.json
حل شد :) 4

2024-07-21 07:49 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.exe
حل شد :) 5

2024-07-21 07:50 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Person.cs
> +    public int id { get; set; }
حل شد پاسکال کردیم .

2024-07-21 07:52 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        foreach (var pj in persons)
دربارش خوندیم دیدیم بخاطر بحث enoumerator  ممکنه foreach هزینه بیشتری در بعضی فیلد ها داشته باشه و بهتره از for عادی استفاده کنیم البته که در مورد linq هم سرچ زدیم و دیدیم linq در کد های پیچیده ای که بخواد خوانا باشه استفاده میشه و از for در حالت عادی کند تره :)

2024-07-21 08:02 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/ReadJson.cs
حل شد 
در مورد sealed هم خوندیم و خوب دلیلی نداره اینجا کلاس هامون از نوع sealed بزاریم و مثلا اگه یه سیستم احراز هویت داشته باشیم برای اون کلاس حداقل منطقیه که sealed بزاریم .

2024-07-21 08:22 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/ReadJson.cs
> +    public int StudentNumber { get; set; }
استفاده کردن از int  وقتی میخوایم با محسابات عددی کار کنیم خیلی بهتره ، و از نظر حافظه هم بهینه تر است و البته در کد ما برای مشخص کردن id دانشجو در آرایه نیاز داریم محاسبه کوچیکی انجام بدیم

2024-07-21 08:22 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        foreach (var sj in scores) studentArr[sj.StudentNumber - 1].studentGrades.Add(sj.Lesson, sj.Score);
حل شد :)

2024-07-21 08:22 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        foreach (var p in studentArr)
حل شد :)

2024-07-21 09:18 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +                @"database\scores.json");
نه خوب نیست براش یه فایل xml ساختیم و مشکل حل شد

2024-07-21 09:36 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        for (var i = 0; i < 3; i++) Console.WriteLine(sortedStudent.ElementAt(i).ToString());
اینا نفهمیدیم مشکل کدمون چی بوده حقیقت ولی در مورد culature insensitive  خوندیم و فهمیدیم باید کدی که میزنیم فارغ از منطقه و فرهنگ برای همه قابل خواندن باشه . خواهشا بعدا بیشتر توضیح بدید مشکل چی بوده : )

2024-07-21 09:39 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        // Sort the array with linq
okk !

2024-07-21 09:45 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        // CW students
کد باید خودش مفهوم برسونه و نام گذاری صحیح خودش باعث خوانش بهتر کد میشه ،بعدا که بتونیم برای کد هامون تست بنویسم شاید نیاز باشه خیلی کم فقط کامنت بزاریم ( همون summery comment ) ، خود یونیت تست ها به خوانش کد کمک میکنه

2024-07-21 09:45 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +    private static List<T> ReadFromJson<T>(string path)
زدیم

2024-07-21 09:46 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +    public static void Main(string[] args)
کلاس زدیم براش و مثلا محسابه معدل دادیم به کلاس دانشگاه که وسط main  نباشه

2024-07-21 14:18 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.pdb
حل شد:) 6

2024-07-21 14:25 UTC, navidnasyry requested changes

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/scores.json
این چرا اینجاس؟؟؟

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/scores.json
directory

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var doc = XDocument.Load(xmlFilePath);
کلاس جدا

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var studentFileManger = new FileManager(pathStudents);
return data

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var scores = scoreFileManger.ReadFromJson<ScoreJsonData>();
---

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +            var tPerson = new Student(persons.ElementAt(i).FirstName, persons.ElementAt(i).LastName,
naming

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Student.cs
> +    public Dictionary<string, double> studentGrades = new();
read about Hashset

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        for (var i = 0; i < scores.Count; i++)
{

}

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Student.cs
> +    public int Id { get; set; }
read about unique keywork

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +            studentArr[scores.ElementAt(i).StudentNumber - 1].studentGrades
linq

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        for (var i = 0; i < scores.Count; i++)
foreach

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/ScoreJsonData.cs
> +public class ScoreJsonData
seales?

2024-07-21 14:25 UTC, navidnasyry commented on phase1/ConsoleApp1/ConsoleApp1/University.cs
> +        for (var i = 0; i < 3; i++) sb.Append(sortedStudent.ElementAt(i).ToString() + "\n");
حلقه نیازه؟؟

2024-07-21 14:26 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +            var tPerson = new Student(persons.ElementAt(i).FirstName, persons.ElementAt(i).LastName,
حذف شد کدش کلا

2024-07-21 14:27 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        for (var i = 0; i < scores.Count; i++)
کدش حذف شد

2024-07-21 14:27 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +            studentArr[scores.ElementAt(i).StudentNumber - 1].studentGrades
حل شد استفاده کردیم :)

2024-07-21 14:27 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        for (var i = 0; i < scores.Count; i++)
نداریم همش جایگزین شد :))))))))))

2024-07-21 14:28 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/University.cs
> +        for (var i = 0; i < 3; i++) sb.Append(sortedStudent.ElementAt(i).ToString() + "\n");
خیر با linq  اوکی شد

2024-07-21 14:30 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/ScoreJsonData.cs
> +public class ScoreJsonData
اوکی کردیم

2024-07-21 14:34 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Student.cs
> +    public Dictionary<string, double> studentGrades = new();
هش ست فقط value هارا ذخیره میکنه و از لحاظ پرفورمنس هم تفاوتی با دیکشنری نداره برای همین هم ما از هش مپ خودمون استفاده میکنیم :)

2024-07-21 14:36 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var scores = scoreFileManger.ReadFromJson<ScoreJsonData>();
دمت گرم کامنت خالی گزاشتی برامون :)

2024-07-21 14:36 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var studentFileManger = new FileManager(pathStudents);
استفاده کردیم ازش و کلاس جدا براش زدیم

2024-07-21 14:37 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var doc = XDocument.Load(xmlFilePath);
زدیم براش

2024-07-21 14:47 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/scores.json
حل شد

2024-07-21 14:59 UTC, AliSK81 requested changes

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/scores.json
move file to source code

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/students.json
move file to source code

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/DataManager/DataManager.cs
> +    public static List<Student> StudentList(List<ScoreJsonData> scores , List<StudentJsonData> students)
اسم متد مناسب نیست

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/DataManager/DataManager.cs
> +    }
reformat file

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/FileReader/FileManager.cs
> +    public string path { get; set; }
take path from method parameter (why?)

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/FileReader/JsonReader.cs
> +    private static String  xmlFilePath = @"../../../app.config.xml";
move file paths to resource (.resx) file

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/Model/University.cs
> +            Students.ElementAt(i).GPA = Students.ElementAt(i).StudentGrades.Values.Sum() / Students.ElementAt(i).StudentGrades.Count;
foreach

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/Model/University.cs
> +        return Students.OrderByDescending(p => p.GPA).Take(3);
تعداد رو از پارامتر تابع بگیریم (چرا؟)

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/app.config.xml
همونطور که گفتم فایل .resx استفاده کنیم

2024-07-21 14:59 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        university.CalculateGPA();
بهتره تابع یک مقداری رو ریترن کنه تا اینکه void باشه
درمورد stateless classes بخونیم
دلیلش رو بهتر توی فازهای کلین کد و یونیت تست میفهمیم

2024-07-21 15:04 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Model/University.cs
> +        return Students.OrderByDescending(p => p.GPA).Take(3);
اوکی شد

2024-07-21 15:05 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Model/University.cs
> +            Students.ElementAt(i).GPA = Students.ElementAt(i).StudentGrades.Values.Sum() / Students.ElementAt(i).StudentGrades.Count;
حل شد :)

2024-07-21 15:10 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/FileReader/FileManager.cs
> +    public string path { get; set; }
کاهش پیچیدگی کد و مدیریت بهتر و خوانایی بهتر کد و تست پذیزی بهتره این کار بکنیم که انجام شد :)

2024-07-21 15:11 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/DataManager/DataManager.cs
> +    }
حل شد :)

2024-07-21 15:13 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/DataManager/DataManager.cs
> +    public static List<Student> StudentList(List<ScoreJsonData> scores , List<StudentJsonData> students)
حل شد

2024-07-21 15:18 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        university.CalculateGPA();
گزاشتیم که یک boolean  برگردونه

2024-07-21 15:19 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/scores.json
حل شده است

2024-07-21 15:19 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/bin/Debug/net8.0/database/students.json
حل شده است

2024-07-22 05:29 UTC, AliSK81 commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        university.CalculateGPA();
CalculateGPA
این متد باید معدل برگردونه

2024-07-22 05:30 UTC, AliSK81 approved these changes
خسته نباشید

2024-07-22 05:54 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        var persons =
ok

2024-07-22 05:56 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/app.config.xml
حل شد استفاده کردیم

2024-07-22 05:57 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Program.cs
> +        university.CalculateGPA();
موردی که هست این قراره معدل کل بچه هارا محسابه کنه و فیلد GPA ذخیره میکنه

2024-07-22 06:02 UTC, mahdijafariii commented on phase1/ConsoleApp1/ConsoleApp1/Student.cs
> +    public int Id { get; set; }
خوندیم در موردش میتونه توی خطوط تکراری بهمون کمک کنه

2024-07-22 06:09 UTC, navidnasyry approved these changes

2024-07-22 06:26 UTC, merged