Phase3
Star-Academy/Summer1403-SE-Team03 pull request #3
Opened 2024-07-25 17:27 UTC by Ftm-Sayadzadeh

phase 03 - first pr

2024-07-25 17:53 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    }
سلام امیدوارم حالتون خوب باشه 
به ما گفتید تحقیق کنیم سوییچ کیس بده و ما تحقیق کردیم و نتیجه این شد وقتی کیس ها کمه if else خوبه و بعد switch و بعد این کاری که ما کردیم 
میخواستم بدونم اینجا ما در تابع search strategy که یک دیکشنری از استراتژی ها داریم اگه بخوایم استراتژی جدیدی اضافه کنیم باید تغییرش بدیم 
خوب اینجا هم به قول خودتون کیس ها اونقدری زیاد نیست که complexity  مهم باشه چرا باید بیایم از دیکشنری استفاده کنیم

2024-07-26 20:07 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    }
آقا سوییچ کیس OpenClose نیست
بخش O در SOLID :)

2024-07-26 20:49 UTC, navidnasyry requested changes

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/FileManager/FileReader.cs
> +public class FileReader
interface

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/FileManager/FileReader.cs
> +        return Resources.databasePath;
databasePath?
مگه دیتابیس داریم؟:)

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/EngineProcessor.cs
> +public class EngineProcessor
interface

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/EngineProcessor.cs
> +    private void SetInvertedIndexDocx()
کلاس با خروجی void پیشنهاد نمیشه

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Program.cs
> +        foreach (var element in result) Console.WriteLine(element);
دو خط آخر دارن یه کاری میکنن دیگه درسته؟:) پس...

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +public class SearchStrategy
interface

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +public class SearchStrategy
why you need interface?

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    public IEnumerable<string> ManageSearchStrategy(string inputSearch)
is it single responsibility ?

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    private void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
single responsibility ?

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    private readonly Dictionary<string, ISearchStrategy> _strategies;
it should be service

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var upperInputSearch = MakeUpperSearchInput(inputSearch);
it is depent to MakeUpperSearchInput class.
read about Dependency inversion prinsiple

2024-07-26 20:49 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +public class SearchStrategy
هیچ کلاسی نباید به کلاسی دیگر وابسته باشد:)
این مورد رو برای همه کلاس ها در نظر بگیرین
و فعلا کامنتی دیگ نمیذارم

2024-07-26 20:52 UTC, navidnasyry requested changes
سعی کینن بجای کلاس های abstract از سینگلتون استفاده کنین

2024-07-27 05:56 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    }
بله اوکی شد

2024-07-27 06:04 UTC, mahdijafariii commented on phase3/phase3/phase3/FileManager/FileReader.cs
> +        return Resources.databasePath;
حل شد منطقیه 👍

2024-07-27 06:26 UTC, mahdijafariii commented on phase3/phase3/phase3/FileManager/FileReader.cs
> +        return Resources.databasePath;
بله بله حل شد

2024-07-27 06:26 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    }
حرف زدیم در موردش اوکی شد

2024-07-27 06:28 UTC, mahdijafariii commented on phase3/phase3/phase3/FileManager/FileReader.cs
> +public class FileReader
کلاسم هنوز singleton  و اومدم یه واسط هم گزاشتم که بیاد استرینگ مسیر داده را بگیره و فایل ریدر روش صدا میزنم اگه نکته ای هست بگید

2024-07-27 06:44 UTC, mahdijafariii commented on phase3/phase3/phase3/Program.cs
> +        foreach (var element in result) Console.WriteLine(element);
حل شد

2024-07-27 08:01 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/EngineProcessor.cs
> +public class EngineProcessor
کلاس از singleton  برداشتم و یدونه اینترفیس براش زدم 
در کل یه اینترفیس اضافه شد و دو خط نیو کردن FileReader و EngineProcessor

2024-07-27 08:02 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/EngineProcessor.cs
> +    private void SetInvertedIndexDocx()
قراره بیاد invertedindex بسازه توی فیلدی که توش تعریف شده قرار بده 
خروجیش میتونیم bool کنیم ولی منطقی نیست

2024-07-27 08:28 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +public class SearchStrategy
حل شد 
وابستگی دیگ نداریم :)
ولی چک کنید خواهشا اگه اوکی بوده کامنت بدید

2024-07-27 09:45 UTC, merged

2024-07-27 12:30 UTC, Ftm-Sayadzadeh commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    public IEnumerable<string> ManageSearchStrategy(string inputSearch)
حل شد

2024-07-27 12:30 UTC, Ftm-Sayadzadeh commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var upperInputSearch = MakeUpperSearchInput(inputSearch);
حل شد