Phase3b
Star-Academy/Summer1403-SE-Team03 pull request #5
Opened 2024-07-27 13:48 UTC by mahdijafariii

pr for phase 3

2024-07-27 15:32 UTC, navidnasyry requested changes
منطق‌های کلاس‌ها نباید به هم وابسته باشن. برای این کار استفاده از interface بسیار اهمیت دارد.
و ...

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/AtLeastOneFilterStrategy.cs
> +        atLeastOne.Add(element.Substring(1));
؟؟؟؟1????

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/MustNotContainFilterStrategy.cs
> +        wordsShouldNotBe.Add(element.Substring(1));
read about trim

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/ISearchStrategy/ISearchStrategy.cs
> +    List<string> ProcessOnWords(List<string> input);
read about immutable and IReadOnlyList

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +    public void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
Single-responsibility

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +    public void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
read about immutable and IReadOnlyList

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +        var defaultStrategy = new MustIncludeFilterStrategy();
use interface

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +            if (strategies.TryGetValue(firstChar, out var strategy))
if element is null

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchResultsFilter.cs
> +            return wordsShouldBeResult.Except(wordsShouldNotBeResult).ToList();
{}

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchResultsFilter.cs
> +        return atLeastOneResult.Intersect(wordsShouldBeResult).Except(wordsShouldNotBeResult).ToList();
long line

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    public SearchStrategy(ISearchStrategy containOneOfWordSearch , ISearchStrategy mustIncludeWord , ISearchStrategy  mustNotContainWord
to many dependencies.

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        _strategies = new Dictionary<string, ISearchStrategy>
read about IReadOnlyDictionary

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        _containOneOfWordSearch = containOneOfWordSearch;
if input value is null?

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    private List<string> SplitSearchInput(string searchInput)
end line

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var atLeastOneResult = _strategies["atLeastOne"].ProcessOnWords(atLeastOne);
extract to const

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    public IEnumerable<string> ManageSearchStrategy(string inputSearch)
is it Single-responsibility

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Program.cs
> +    //testing merge
?

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Program.cs
> +        foreach (var element in result) Console.WriteLine(element);
extract output to class and interface

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchImplemention/MustNotContainWord.cs
> +            .ToList();
how many ToList()?:)))

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        FileReader fileReader = new FileReader();
var

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +            { new ExtraSpaceRemover(), new PunctuationRemover(), new UpperCaseMaker() };
reformat

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +        foreach (var operation in operations) result = operation.Execute(result);
??

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +        foreach (var operation in operations) result = operation.Execute(result);
refactor

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +        var data = FileProcessor.ProcessDocumentsForIndexing(dataFiles);
is it depend to class?

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +        var data = FileProcessor.ProcessDocumentsForIndexing(dataFiles);
use interface

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +    public static List<DataFile> ProcessDocumentsForIndexing(List<DataFile> docx)
این کلاس داره یه جایی استفاده میشه؟
اونجاها که داره استفاده میشه به کلاس وابستس؟ 
این درسته یا نه؟ بهتره چیکار کنیم؟

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +    public static Dictionary<string, List<string>> BuildInvertedIndex(List<DataFile> docs)
...

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +}
long method

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +            foreach (var elementWord in words)
{}

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +                    List<string> values = new() { element.FileName };
var

2024-07-27 15:32 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/FileProcessor/PunctuationRemover.cs
> +        const string pattern = @"[^A-Za-z0-9]";
how about 
const string pattern = @"\W";

2024-07-28 05:11 UTC, AliSK81 requested changes

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/FileManager/FileReader.cs
> +public class FileReader : IFileReader
چه نوع فایلی؟

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/FileManager/FileReader.cs
> +            data.Add(new DataFile { FileName = Path.GetFileName(file), Data = File.ReadAllText(file) });
linq

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    public Dictionary<string, List<string>> InvertedIndexDictionary { get; set; }
encapsulation is violated

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/EngineProcessor/IEngineProcessor.cs
> +    void SetInvertedIndexDocx(List<DataFile> dataPath);
there is no way to access inverted index through interface

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/FileProcessor/ExtraSpaceRemover.cs
> +        const string pattern = @"\s+";
move to class static readonly property

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +    public static Dictionary<string, List<string>> BuildInvertedIndex(List<DataFile> docs)
long method

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +public class InvertedIndexBuilder
interface

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        EngineProcessor engineProcessor = new EngineProcessor();
Dependency Inversion Principle (DIP) violated

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/IFilterStrategy/IFilterSearchStrategy.cs
> +    void Apply(string element, List<string> atLeastOne, List<string> wordsShouldBe, List<string> wordsShouldNotBe);
too many params

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/MustIncludeFilterStrategy.cs
> +    public void Apply(string element, List<string> atLeastOne, List<string> wordsShouldBe, List<string> wordsShouldNotBe)
unused parameters

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/MustNotContainFilterStrategy.cs
> +    {
unused params

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +    public void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
long method

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    private readonly SearchResultsFilter _searchResultsFilter;
inject interfaces to avoid DIP violation

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
این رشته ها تو جاهای مختلف کد استفاده شده اگه اشتباه تایپی داشته باشیم یه جا چی میشه؟

2024-07-28 05:11 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
فکتوری میتونیم استفاده کنیم؟

2024-07-28 05:54 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/AtLeastOneFilterStrategy.cs
> +        atLeastOne.Add(element.Substring(1));
اوکی شد

2024-07-28 05:54 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/MustNotContainFilterStrategy.cs
> +        wordsShouldNotBe.Add(element.Substring(1));
بله حل شد

2024-07-28 05:56 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/ISearchStrategy/ISearchStrategy.cs
> +    List<string> ProcessOnWords(List<string> input);
حل شد

2024-07-28 06:21 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +    public void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
حل شد با استفاده از interface

2024-07-28 06:22 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +    public void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
حل شد

2024-07-28 06:22 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +        var defaultStrategy = new MustIncludeFilterStrategy();
حل شد

2024-07-28 06:22 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +            if (strategies.TryGetValue(firstChar, out var strategy))
دیگ نداریمش کلا

2024-07-28 06:23 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchResultsFilter.cs
> +            return wordsShouldBeResult.Except(wordsShouldNotBeResult).ToList();
گزاشتیم براش

2024-07-28 06:23 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchResultsFilter.cs
> +        return atLeastOneResult.Intersect(wordsShouldBeResult).Except(wordsShouldNotBeResult).ToList();
اوکی شده

2024-07-28 06:33 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    public SearchStrategy(ISearchStrategy containOneOfWordSearch , ISearchStrategy mustIncludeWord , ISearchStrategy  mustNotContainWord
وابستگی هارا از طریق constructor فرستادیم چیکار باید بکنیم ؟

2024-07-28 06:41 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        _strategies = new Dictionary<string, ISearchStrategy>
اوکی شد

2024-07-28 06:48 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        _containOneOfWordSearch = containOneOfWordSearch;
add custom exeption

2024-07-28 06:52 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    private List<string> SplitSearchInput(string searchInput)
حل شد

2024-07-28 06:58 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var atLeastOneResult = _strategies["atLeastOne"].ProcessOnWords(atLeastOne);
بله اوکی شد

2024-07-28 06:58 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    public IEnumerable<string> ManageSearchStrategy(string inputSearch)
بله سینگل هست

2024-07-28 07:42 UTC, mahdijafariii commented on phase3b/phase3/phase3/Program.cs
> +        foreach (var element in result) Console.WriteLine(element);
حل شد ولی یه سوال داریم حضوری باید بپرسیم

2024-07-28 07:42 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchImplemention/MustNotContainWord.cs
> +            .ToList();
درست شد

2024-07-28 07:44 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        FileReader fileReader = new FileReader();
حله

2024-07-28 07:45 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +            { new ExtraSpaceRemover(), new PunctuationRemover(), new UpperCaseMaker() };
بله اوکی شد

2024-07-28 07:46 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +        foreach (var operation in operations) result = operation.Execute(result);
حل شد ولی ؟؟ قضیش چیه مشکل کجاست ؟

2024-07-28 08:16 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +        var data = FileProcessor.ProcessDocumentsForIndexing(dataFiles);
حل شد

2024-07-28 08:17 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/FileProcessor/FileProcessor.cs
> +    public static List<DataFile> ProcessDocumentsForIndexing(List<DataFile> docx)
حل شد. بهتره اینترفیس بزنیم...

2024-07-28 08:22 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +    public static Dictionary<string, List<string>> BuildInvertedIndex(List<DataFile> docs)
حل شد اینترفیس زدیم :)

2024-07-28 08:34 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +}
List<string> values = new() { element.FileName };
                    invertedData.Add(elementWord, values); 
به جای این توی خودش نیو کردیم و بخش مربوط به اسپیلیت کردن هم یه تابع جدا کردیم.

2024-07-28 08:35 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +            foreach (var elementWord in words)
حل شد :))))

2024-07-28 08:36 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +                    List<string> values = new() { element.FileName };
حل شد :)

2024-07-28 08:37 UTC, msmahdinejad commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +public class SearchStrategy
interface?
اگه استراتژی دیگه ای بخوایم پیاده سازی کنیم

2024-07-28 08:37 UTC, msmahdinejad commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +        var invertedData = new Dictionary<string, List<string>>();
not open/close
اینودرتد ایندکس فقط مخصوص سرچ بین داک هاست

2024-07-28 08:38 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/FileProcessor/PunctuationRemover.cs
> +        const string pattern = @"[^A-Za-z0-9]";
حل شد :)

2024-07-28 08:46 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/FileManager/FileReader.cs
> +public class FileReader : IFileReader
TextFileReader

2024-07-28 08:52 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/FileManager/FileReader.cs
> +            data.Add(new DataFile { FileName = Path.GetFileName(file), Data = File.ReadAllText(file) });
حل شد :)

2024-07-28 08:55 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    public Dictionary<string, List<string>> InvertedIndexDictionary { get; set; }
private set

2024-07-28 09:01 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/EngineProcessor/IEngineProcessor.cs
> +    void SetInvertedIndexDocx(List<DataFile> dataPath);
حل شد یه گتر اضافه کردیم برای دسترسی :))

2024-07-28 09:08 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/FileProcessor/ExtraSpaceRemover.cs
> +        const string pattern = @"\s+";
حل شد

2024-07-28 09:09 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +    public static Dictionary<string, List<string>> BuildInvertedIndex(List<DataFile> docs)
حل شد ولی بهترش چی میشه؟؟

2024-07-28 09:09 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +public class InvertedIndexBuilder
حله

2024-07-28 09:11 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/IFilterStrategy/IFilterSearchStrategy.cs
> +    void Apply(string element, List<string> atLeastOne, List<string> wordsShouldBe, List<string> wordsShouldNotBe);
حل شده

2024-07-28 09:11 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/MustIncludeFilterStrategy.cs
> +    public void Apply(string element, List<string> atLeastOne, List<string> wordsShouldBe, List<string> wordsShouldNotBe)
حل شده

2024-07-28 09:11 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/FilterStrategy/SearchStrategyImplemention/MustNotContainFilterStrategy.cs
> +    {
حل شده

2024-07-28 12:41 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +    public static Dictionary<string, List<string>> BuildInvertedIndex(List<DataFile> docs)
حل شد

2024-07-28 12:41 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        EngineProcessor engineProcessor = new EngineProcessor();
حل شد

2024-07-28 12:42 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +    public void ManageInputSearchStrategy(List<string> splitInput, out List<string> atLeastOne,
حلل شد :)

2024-07-28 13:38 UTC, Ftm-Sayadzadeh commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
ما اومدیم دیکشنری زدیم که open close رعایت کنیم ولی در لحظه آخر گفتید بریم Factory بزنیم 
خوب اوکیه ولی موردی هست که توی design pattern factory در اینتفریسی که میاد sign میگیره و استراتژی برمیگردونه باید Switch بزنیم و دوباره داریم open close نقض میکنیم !!! 
آقای نصیری گفتن بهتره بیایم استراتژی هارا توی یه لیست بریزیم و بر اساس عدد enum که برمیگردونه بریم به عنصر اون لیست دسترسی پیدا کنیم نظر شما هم بدونیم خیلی خوب میشه : )

2024-07-28 14:46 UTC, rajabi-m reviewed
یه کار پیش اومد برام نتونستم ادامه بدم.

2024-07-28 14:46 UTC, rajabi-m commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/IInvertedIndexBuilder.cs
> +    Dictionary<string, List<string>> BuildInvertedIndex(List<DataFile> docs);
اینجا مشکل primitive obsession دارین بهتره از یه کلاس wrapper استفاده کنین

2024-07-28 15:07 UTC, mobinbr commented on phase3b/phase3/phase3/IO/InputManager/TextFileReader.cs
> +    }
این تابع اینجا صرفا تابع ReadFilesFromFolder رو صدا میزنه و هیچ استفاده دیگه ای نداره پس چرا تعریف شده؟
بخاطر این بوده که تو IFileReader تعریفش کردین؟

2024-07-29 05:34 UTC, navidnasyry requested changes

2024-07-29 05:34 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +            }
extract method

2024-07-29 05:34 UTC, navidnasyry commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        // کامنت گزاشتم که ببینید کانستراکتور انجین پراسسر داره یدونه file processor نیو میکنه و آیا این اوکیه ؟ یا باید به نحو دیگ ای باشه ؟
کامنت فارسی؟:(((
اصلا چرا کامنت؟؟؟
کد باید اونقد خوانا باشه نیاز به کامنت نداشته باشه

2024-07-29 05:34 UTC, navidnasyry commented on phase3b/phase3/phase3/IO/InputManager/TextFileReader.cs
> +    }
چرا تو پابلیک پیاد نشده؟

2024-07-29 05:34 UTC, navidnasyry commented on phase3b/phase3/phase3/Models/ConstProperties.cs
> +public static class ConstProperties
اسم کلاس کلیه. مشخص نیست حاوی چه کانست هایی هست

2024-07-29 05:34 UTC, navidnasyry commented on phase3b/phase3/phase3/Models/ConstProperties.cs
> +    public static readonly string _patternPunctuation = @"\W";
const string

2024-07-29 05:34 UTC, navidnasyry commented on phase3b/phase3/phase3/Models/QueryConstants.cs
> +    public static readonly string mustNotContainSign = "-";
const

2024-07-29 05:59 UTC, mahdijafariii commented on phase3b/phase3/phase3/IO/InputManager/TextFileReader.cs
> +    }
آره اوکیه یکیش برای وقتی بود که path  داشتیم واقعا دیگ حذفش نکردیم
مرسی

2024-07-29 06:01 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +            }
بله حل شد

2024-07-29 06:01 UTC, navidnasyry approved these changes

2024-07-29 06:01 UTC, navidnasyry commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchImplemention/MustNotContainWord.cs
> +        sign = "-";
const

2024-07-29 06:01 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        // کامنت گزاشتم که ببینید کانستراکتور انجین پراسسر داره یدونه file processor نیو میکنه و آیا این اوکیه ؟ یا باید به نحو دیگ ای باشه ؟
سوال ازتون پرسیده بودیم کامنت نبود 😂

2024-07-29 06:02 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        // کامنت گزاشتم که ببینید کانستراکتور انجین پراسسر داره یدونه file processor نیو میکنه و آیا این اوکیه ؟ یا باید به نحو دیگ ای باشه ؟
پاکش کرده بودیم نمیدونم چرا هست الان البته

2024-07-29 06:04 UTC, mahdijafariii commented on phase3b/phase3/phase3/IO/InputManager/TextFileReader.cs
> +    }
قبلا از یه آدرسی میخوندیم ولی الان اوکیه باید توی همون پابلیک باشه

2024-07-29 06:06 UTC, mahdijafariii commented on phase3b/phase3/phase3/Models/ConstProperties.cs
> +public static class ConstProperties
حل شد

2024-07-29 06:09 UTC, mahdijafariii commented on phase3b/phase3/phase3/Models/ConstProperties.cs
> +    public static readonly string _patternPunctuation = @"\W";
حله

2024-07-29 06:10 UTC, mahdijafariii commented on phase3b/phase3/phase3/Models/QueryConstants.cs
> +    public static readonly string mustNotContainSign = "-";
حل شد

2024-07-29 06:11 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchImplemention/MustNotContainWord.cs
> +        sign = "-";
اصلا ازش استفاده نکردیم بعدش که const گزاشتیم

2024-07-29 06:12 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
پس از پاسی از وقت که گذشت آقای نصیری اسفتاده از دیکشنری پیشنهاد دادن و کد خیلی خیلی خیلی بهتر و خوانا تر هم شد

2024-07-29 06:14 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +    private readonly SearchResultsFilter _searchResultsFilter;
بله بله حل شد

2024-07-29 06:14 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +        var invertedData = new Dictionary<string, List<string>>();
باشه

2024-07-29 06:16 UTC, mahdijafariii commented on phase3b/phase3/phase3/Program.cs
> +    //testing merge
این من گزاشته بودم برای تست کردن اینکه فایل هام میاد برای مرج یا نه و حل شد

2024-07-29 06:33 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
توی کارگاه گفتیم فکتوری رو چطور پیاده سازی کنیم که open close نقض نشه

2024-07-29 06:33 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
اینکه منطق رو ببریم تو فکتوری یه پله بهتره باز
حداقل وظیفه اونه

2024-07-29 06:34 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
میتونید توی  فکتوری for بزنید روی لیست استراتژی ها و تایپ رو از خودشون بپرسید و با تایپ ورودی مقایسه کنید

2024-07-29 06:51 UTC, AliSK81 requested changes
لطفا:
1. نامگذاری ها تا میتونه بهتر بشه
از اسم اینترفیس و توابعش بهفمیم چیکار میکنه یا summary بنویسیم
مثلا اسم اینترفیس IEngineProcessor اصلا معلوم نیست کارش چیه
2. اکسپشن های کاستوم رو هندل کنیم و کاری به اکسپشن های سیستمی نداشته باشیم
3. تابعی که void هست احتمالا ورودی هارو تغییر میده، داخل کلاس چیزی ست میکنه و گتر داریم براش یا..
خیلی جاها وید خوب نیست و در صورت امکان همون تابع خروجی رو ریترن کنه

2024-07-29 06:51 UTC, AliSK81 commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +        _invertedIndexBuilder = invertedIndexBuilder;
check for arugment null exception

2024-07-29 06:51 UTC, AliSK81 commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    }
میتونه به arrow function تبدیل بشه
public Dictionary<String, List<String>> InvertedIndex => InvertedIndexDictionary;

2024-07-29 06:51 UTC, AliSK81 commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    }
هرچند من فکر میکنم این کلاس طراحی خوبی نداره
1. از اسمش نمیشه حس گرفت دقیقه چه کاری میکنه
اصل SRP نقض شده

2024-07-29 06:51 UTC, AliSK81 commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    public void SetInvertedIndexDocx(List<DataFile> dataFiles)
چرا خود این تابع InvertedIndex رو ریترن نکنه

2024-07-29 06:51 UTC, AliSK81 commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        // کامنت گزاشتم که ببینید کانستراکتور انجین پراسسر داره یدونه file processor نیو میکنه و آیا این اوکیه ؟ یا باید به نحو دیگ ای باشه ؟
کامنت توی کد نباشه

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Exceptions/InvalidInputException.cs
> +{
جایی هندلش کردیم؟

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Models/QueryConstants.cs
> +    public const string atLeastOneSign = "+";
PascalCase for const properties

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Models/RegexPatternConst.cs
> +    public const string _patternPunctuation = @"\W";
PascalCase

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    }
منظورم این بود میتونه توابعی برای تغییر روی InvertedIndexDictionary ایجاد بشه
البته با این منطقی که میبینم بهتره تابع SetInvertedIndexDocx وید نباشه و چیزی که میسازه رو ریترن کنه

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    }
این گتر اضافه کردن مزیت خاصی ایجاد نکرده

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/InputHandler/SearchStrategyImplemention/MustIncludeInputStrategy.cs
> +                wordSouldBe.Add(word);
const string

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchImplemention/MustIncludeWord.cs
> +            .Aggregate((result, next) => result.Intersect(next).ToList());
long line

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +        }
چه مزیتی ایجاد کرده؟

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _searchStrategyFactory.GetValueOfKey(QueryConstants.mustNotContainSign).ProcessOnWords(wordsShouldNotBe);
factory design pattern

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactory.cs
> +    }
توی اینترفیس استراتژی یه کلید تعریف کنید و برای توی هر پیاده سازی ایمپلمنت کنید
میتونید فور بزنید روی استراتژی ها اونی که کلیدش مچ شد ریترن کنید
ISearchStrategy.Key

2024-07-29 06:51 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactory.cs
> +    }
این دیپندنسی هارو هم از کانستراکتور بگیرید! DIP

2024-07-29 07:21 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _strategies["wordsShouldNotBe"].ProcessOnWords(wordsShouldNotBe);
اها حله

2024-07-29 07:27 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/QueryProcessor/SearchOperation.cs
> +        // کامنت گزاشتم که ببینید کانستراکتور انجین پراسسر داره یدونه file processor نیو میکنه و آیا این اوکیه ؟ یا باید به نحو دیگ ای باشه ؟
بخدا اینا ما نداریم توی کد حتی توی گیت هم چک کردیم نیست 
شما روی فاز سه گزاشتید این تک کامنتو

2024-07-29 07:31 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    public void SetInvertedIndexDocx(List<DataFile> dataFiles)
بله منطقی بود اوکی شد

2024-07-29 07:32 UTC, mahdijafariii commented on phase3b/phase3/phase3/Exceptions/InvalidInputException.cs
> +{
بله

2024-07-29 07:33 UTC, mahdijafariii commented on phase3b/phase3/phase3/Models/QueryConstants.cs
> +    public const string atLeastOneSign = "+";
حل شد

2024-07-29 07:34 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    }
یه تابعش کردیم

2024-07-29 07:39 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/InputHandler/SearchStrategyImplemention/MustIncludeInputStrategy.cs
> +                wordSouldBe.Add(word);
بله حل شد

2024-07-29 07:40 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchImplemention/MustIncludeWord.cs
> +            .Aggregate((result, next) => result.Intersect(next).ToList());
حل شد

2024-07-29 07:53 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +        }
وقتی کاربر متنی وارد نکنه اکسپشن پرتاب میشه

2024-07-29 07:57 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var wordsShouldNotBeResult = _searchStrategyFactory.GetValueOfKey(QueryConstants.mustNotContainSign).ProcessOnWords(wordsShouldNotBe);
این نمیشه فور زد باید توی لیست های مختلف ریخته بشه و باید دستی انجام بدیم
حالا اگه منظور خاص دیگ ای بوده بفرمایید

2024-07-29 07:57 UTC, mahdijafariii commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactory.cs
> +    }
این خودش توی کانستراکتور 
منظورتون اینه بیایم فیلد تعریف کنیم و توی کانستراکتور ست کنیم بعد اد کنیم به strategies ?

2024-07-29 08:02 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +    }
حل شد اسمش عوض کردیم ولی arrow function نمیتونه باشه دیگ چون داریم ست میکنیم و برمیگردونیم (solid) رعایت شده البته الان دیگ

2024-07-29 08:08 UTC, mahdijafariii commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +        _invertedIndexBuilder = invertedIndexBuilder;
حلش کردیم

2024-07-29 08:45 UTC, AliSK81 commented on phase3b/phase3/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactory.cs
> +    }
منظورم این بود 
List<ISearchStrategy> strategies
رو توی کانستراکتور بگیریم

بعد موقعی که میخوایم استراتژی رو پیدا کنیم توی تابع GetValueOfKey بجای اینکه از دیکشنری بخونیم اینو ریترن کنیم:
_strategies.Single(x => x.Key == key)

2024-07-29 08:45 UTC, AliSK81 approved these changes
Approved with suggestions

2024-07-29 09:58 UTC, mobinbr approved these changes

2024-07-29 10:04 UTC, merged

2026-09-22 17:51 UTC, prangan-tooteja-ai commented on phase3/phase3/phase3/Processor/EngineProcessor/EngineProcessor.cs
> +        _invertedIndexBuilder = invertedIndexBuilder;
Done: PENDING now explained inline, and the ENQUEUED line references it.