Phase4
Star-Academy/Summer1403-SE-Team03 pull request #8
Opened 2024-07-30 15:54 UTC by mahdijafariii

سلام سه کلاس تست دیگ داریم که فردا میزنیم .

2024-07-31 06:32 UTC, navidnasyry requested changes

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/UnitTest1.cs
> +    }
؟

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/InvertedIndexManager/InvertedIndexBuilderTest.cs
> +
AAA

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/InvertedIndexManager/InvertedIndexBuilderTest.cs
> +        var indexBuilder = new InvertedIndexBuilder();
_sut

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/InvertedIndexManager/InvertedIndexBuilderTest.cs
> +        var indexBuilder = new InvertedIndexBuilder();
abbreviation of service under test

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +    public void ExtraSpaceRemover_ShouldDeleteExtraSpaces_WhenInputContainsMultipleSpaces()
حالت های دیگر برای این متد

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +        var testData = new List<DataFile>
naming

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +            new DataFile { FileName = "file1", Data = "sa  laa mmm khu   biiii  manam khuuuuuuu            bam" },
تست‌ها پیچیدن
تا جایی که میشه تست‌هامون باید ریز و کوچیک باشه و از ساده‌ترین حالت شروع به تست نویسی کنیم
read about **unit** test

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +        var resultExtraSpaceRemover = new ExtraSpaceRemover().Execute(testData);
_sut 
توی کانستراکتور میتونه ایجاد بشه

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +        };
test edge cases

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +        };
unexpected inputs

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +        };
also start testing with simpler cases

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/UpperCaseMakerTest.cs
> +            Assert.Equal(expectedTestData[i].Data, resultUpperMaker[i].Data);
راهی غیر از حلقه زدن نیست؟

2024-07-31 06:32 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/UpperCaseMakerTest.cs
> +            Assert.Equal(expectedTestData[i].Data, resultUpperMaker[i].Data);
read about equal method of class

2024-07-31 11:04 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/UnitTest1.cs
> +    }
حل شد ...

2024-07-31 11:05 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/InvertedIndexManager/InvertedIndexBuilderTest.cs
> +
حله

2024-07-31 11:07 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/InvertedIndexManager/InvertedIndexBuilderTest.cs
> +        var indexBuilder = new InvertedIndexBuilder();
حله

2024-07-31 11:20 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +        var testData = new List<DataFile>
اسمش عوض شد

2024-07-31 11:20 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +            new DataFile { FileName = "file1", Data = "sa  laa mmm khu   biiii  manam khuuuuuuu            bam" },
حله

2024-07-31 11:20 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +        var resultExtraSpaceRemover = new ExtraSpaceRemover().Execute(testData);
حله

2024-07-31 12:01 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/PreProcessor/UpperCaseMakerTest.cs
> +            Assert.Equal(expectedTestData[i].Data, resultUpperMaker[i].Data);
به جای حلقه از SequenceEqual زدیم

2024-07-31 12:03 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +        };
ما سه تا اینترفیس قبلی بصورت کامل تست کردیم در حالت های قبلی الان صرفا میخوایم ببینیم سه تاش باهم کار میکنه یا نه واقعا فکر نمیکنیم نیازی به تست های بیشتر باشه

2024-07-31 15:01 UTC, navidnasyry requested changes

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Exceptions/InvalidInputException.cs
> +    public InvalidInputException() : base("Invalid Input :)))))))")
یه کامنتی باشه که مشخص باشه چه خطایی در چه جایی و چه زمانی

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Exceptions/InvalidInputException.cs
> +    public InvalidInputException() : base("Invalid Input :)))))))")
read about default constructor of Exception

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/EngineProcessor/ISearchIndexManager.cs
بهتره interfaceها توی یه فولدی Abstraction باشه

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/EngineProcessor/SearchIndexManagerTest.cs
> +        // arrange
Arrange

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/EngineProcessor/SearchIndexManagerTest.cs
> +        // arrange
Act

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/EngineProcessor/SearchIndexManagerTest.cs
> +        // arrange
Assesrt

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +    public void ProcessDocumentsForIndexing_ShouldApplyAllTextOperationsCorrectly()
when...

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +    public void ProcessDocumentsForIndexing_ShouldApplyAllTextOperationsCorrectly()
when...

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/PreProcessor/FileProcessor.cs
> +        return operations.Aggregate(docx, (current, operation) => operation.Execute(current));
چه اتفاقی میوفته وقتی اینجا توی متد نیو میکنین؟؟؟؟
قبول دارین برای تست این متد اون کلاس ‌ها هم اجرا و نیو میشن؟ آیا میتونین mockش کنین؟ نه
پس چیکار کنیم؟
open close نیست

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/EngineProcessor/SearchIndexManager.cs
> +            throw new ArgumentNullException();
test

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/EngineProcessor/SearchIndexManager.cs
> +            throw new ArgumentNullException();
send nameof(param) to ArgumentNullException constructor

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/EngineProcessor/SearchIndexManager.cs
> +            throw new ArgumentNullException();
_fileProcessor = fileProcessor ?? new ArgumentNullException(nameof(fileProcessor))

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +        foreach (DataFile element in docs)
test if docs null

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/PreProcessor/ExtraSpaceRemover.cs
> +            FileName = element.FileName,
test if element is null

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3/Processor/PreProcessor/ExtraSpaceRemover.cs
> +    public List<DataFile> Execute(List<DataFile> docx)
if input null

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/InputHandler/SearchStrategyImplemenation/AtLeastOneInputStrategyTest.cs
> +        Assert.True(expectedTestData.Count == result.Count);
دقیق تر Assertion داشته باشیم

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/InputHandler/SearchStrategyImplemenation/AtLeastOneInputStrategyTest.cs
> +        Assert.True(expectedTestData.Count == result.Count);
تست جدید برای
لیستی از ورودی تست شود که چند کلمه بدون 
+
دارد

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/InputHandler/SearchStrategyImplemenation/MustIncludeInputStrategyTest.cs
> +        Assert.True(expectedTestData.Count == result.Count);
دقیق تر

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/InputHandler/SearchStrategyImplemenation/MustIncludeInputStrategyTest.cs
> +    public void MustIncludeInputStrategy_ShouldNotContainAnyWord_WhenInputNotContainAnyWord()
مثل کامنت‌ قبلی برای تست جدید

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/InputHandler/SearchStrategyImplemenation/MustNotContainInputStrategyTest.cs
> +}
مثل کامنت‌های AtLeastOne

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchImplemention/ContainOneWordSearchTest.cs
> +        Assert.Equal(result, resultProcessOnWords);
Assert.Equal
همیشه برای چک کردن دیکشنری مناسبه؟

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchImplemention/ContainOneWordSearchTest.cs
> +        Assert.Equal(result, resultProcessOnWords);
ایا اینجا داره درست کار میکنه؟ اشتباه pass نشه

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchImplemention/ContainOneWordSearchTest.cs
> +    public void ProcessOnWord_ShouldReturnEmptyList_WhenInputContainNoWord()
how about 
when input is null

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchImplemention/ContainOneWordSearchTest.cs
> +        Assert.Equal(result, resultProcessOnWords);
پارامتر اول باید Expected باشه یا result?چرا

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchImplemention/ContainOneWordSearchTest.cs
> +
؟

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchQueryParserTest.cs
> +            wordsShouldNotBe.SequenceEqual(expectedWordsShouldNotBe));
هر تست بهتره یه چیزو assert کنه

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchResultsFilterTest.cs
> +    public void GetResult_ShouldReturnExpectedDataFile_WhenInputHaveAllTypeOfResult()
دقیق توی اسم تست مشخص کنیم expected چه ویژگی داره

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchResultsFilterTest.cs
> +    public void GetResult_ShouldReturnExpectedDataFile_WhenInputHaveAllTypeOfResult()
همینطور برای بقیه تست ها

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactoryTest.cs
> +        _sut = new SearchStrategyFactory();
این دیپندسی ماک شده چه ارتباطی با sut‌داره؟‌ توی کانستراکتور نگرفته که

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactoryTest.cs
> +    public void GetValueOfKey_ShouldReturnIInputManagementObject_WhenInputIsAtLeastOneSign()
بخش Should رو دقیق تر بنویسیم

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyTest.cs
> +        // act
اینا arrange هستن

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyTest.cs
> +        var result = _sut.ManageSearchStrategy("+test1 test2 -test3");
این Act هست

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyTest.cs
> +            .Setup(x => x.GetResult(It.Ref<List<string>>.IsAny, It.Ref<List<string>>.IsAny, It.Ref<List<string>>.IsAny))
چرا ورودی هارو دقیق مشخص نکنیم؟‌ اینکه any‌بزنیم چه اشکالی داره؟

2024-07-31 15:01 UTC, navidnasyry commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyTest.cs
> +        Assert.IsAssignableFrom<IEnumerable<string>>(result);
دقیق تر assert کنیم

2024-08-02 15:34 UTC, mahdijafariii commented on phase4/phase3/phase3/Exceptions/InvalidInputException.cs
> +    public InvalidInputException() : base("Invalid Input :)))))))")
اوکیه

2024-08-02 16:10 UTC, mahdijafariii commented on phase4/phase3/phase3Test/Processor/PreProcessor/FileProcessorTest.cs
> +    public void ProcessDocumentsForIndexing_ShouldApplyAllTextOperationsCorrectly()
یادمون رفته بود

2024-08-02 16:10 UTC, mahdijafariii commented on phase4/phase3/phase3/Processor/EngineProcessor/ISearchIndexManager.cs
این در موردش توی کارگاه بحث کردیم خودمون هم خوندیم 
خیلی برمیگرده به ساختار پروژه 
توی حالتی که ما اینترفیس هارا گزاشتیم اینترفیس ها نزدیک به پیاده سازی 
درسته که اگه پروژه بزرگ باشه خیلی خیلی سخت و پیچیده و گیج کننده میشه ولی از اونجایی که پروژه ما کوچیکه تصمیمون این بود نزدیک پیاده سازی ها باشه

2024-08-03 06:05 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +    public void ExtraSpaceRemover_ShouldDeleteExtraSpaces_WhenInputContainsMultipleSpaces()
حل شد

2024-08-03 06:05 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/EngineProcessor/SearchIndexManagerTest.cs
> +        // arrange
حله

2024-08-03 06:25 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3/Processor/PreProcessor/FileProcessor.cs
> +        return operations.Aggregate(docx, (current, operation) => operation.Execute(current));
ما تغییرش دادیم و از فکتوری استفاده کردیم ولی این باعث میشه اینترفیس بزنیم و چندجای دیگه به عنوان پارامتر تابع این فکتوری نیو بشه. آیا این کار درسته؟ چون اگه استاتیک بود خیلی راحت تر بود... اصولیش چطوریه؟

2024-08-03 06:30 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3/Processor/EngineProcessor/SearchIndexManager.cs
> +            throw new ArgumentNullException();
جالب بود :)

2024-08-03 06:35 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3/Processor/PreProcessor/FileProcessor.cs
> +        return operations.Aggregate(docx, (current, operation) => operation.Execute(current));
حل شد

2024-08-03 06:45 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3/Processor/PreProcessor/ExtraSpaceRemover.cs
> +            FileName = element.FileName,
حله

2024-08-03 07:11 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchImplemention/ContainOneWordSearchTest.cs
> +
برای وقتیه که اشتراکی پیدا نمیکنه و خب بابید لیست خالی بفرسته.  منظور شما همین بود یا چیز دیگهه ای؟

2024-08-03 07:17 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchQueryParserTest.cs
> +            wordsShouldNotBe.SequenceEqual(expectedWordsShouldNotBe));
حله چند تا تست کردیم

2024-08-03 07:31 UTC, Ftm-Sayadzadeh commented on phase4/phase3/phase3Test/Processor/QueryProcessor/SearchStrategy/SearchStrategyTest.cs
> +            .Setup(x => x.GetResult(It.Ref<List<string>>.IsAny, It.Ref<List<string>>.IsAny, It.Ref<List<string>>.IsAny))
ما اینجا مشخص کردیم از نوع استرینگ میخوایم
ولی در کل مشکلش اینه که ممکنه بخشی از لاجیک کد وابسته باشه به ورودی که داره میگیره و بهتره که نوعش دقیق مشخص باشه ولی اینجا اهمیتی نداره

2024-08-03 09:28 UTC, AliSK81 approved these changes
خسته نباشید
کامنت ها رو دیدین ریزالو کنید مرج کنید (لزومی نداره تغییرات رو اعمال کنید)

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/EngineProcessor/Abstractions/ISearchIndexManager.cs
> +    Dictionary<string, List<string>> GetInvertedIndex(List<DataFile> dataFiles);
بهتر بود ساختار inverted index (دیکشنری از استرینگ به لیست..) wrap میشد توی یه کلاس 
احتمالا برای فاز بعد ساختار inverted index یکم تغییر کنه و کدها هم نیاز به تغییر داده باشن

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/InvertedIndexManager/InvertedIndexBuilder.cs
> +            throw new NullReferenceException();
ArgumentNullException(nameof(docs))

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/PreProcessor/ExtraSpaceRemover.cs
> +            throw new NullReferenceException();
ArgumentNullException.ThrowIfNull(docs);
or
throw new ArgumentNullException(nameof(docs));

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/PreProcessor/FileProcessorFactory/ProcessFactory.cs
> +}
فکتوری باید یه تایپ رو فقط برگردونه
لیست تایپ های موردنیاز رو باید از di بگیریم

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchImplemention/ContainOneOfWordSearch.cs
> +        return finalResult.ToList();
یکبار کافیه

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchImplemention/ContainOneOfWordSearch.cs
> +        _searchOperation = searchOperation;
check for argument null exception

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchImplemention/MustIncludeWord.cs
> +            throw new InvalidOperationException("Input list cannot be empty");
.resx

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchStrategy/SearchOperation.cs
> +        return documents;
return documents ?? [];

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchStrategy/SearchQueryParser.cs
> +        wordsShouldNotBe = new List<string>(new MustNotContainInputStrategy().Apply(splitInput));
اینجا میتونستیم factory بزنیم

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategy.cs
> +        var splitSearchInput = searchInput.Split(" ").ToList();
تابع split() بدون پارامتر با whitespace جدا میکنه به طور دیفالت

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3/Processor/QueryProcessor/SearchStrategy/SearchStrategyFactory/SearchStrategyFactory.cs
> +        };
اگه از کانستراکتور میگرفتیم دیپندنسی هارو DIP نقض نمیشد

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3Test/IO/InputManager/TextFileReaderTest.cs
> +    private readonly string _testDirectory;
private const string TestDirectory;

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3Test/IO/OutPutManager/ConsoleOutPutTest.cs
> +        Assert.IsType<List<string>>(result);
دقیق نیست
ممکنه تابع OutputProcess توی حالتی درست کار نکنه اما این تست pass بشه

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3Test/Processor/EngineProcessor/SearchIndexManagerTest.cs
> +        var exception = Record.Exception(() => new SearchIndexManager(null, _mockInvertedIndexBuilder.Object));
Record.Exception 
چه مزیتی ایجاد میکنه نسبت به این که خودمون action تعریف کنیم؟

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +        var resultExtraSpaceRemover = _sut.Execute(testData);
قواعد نامگذاری هارو توی تست رعایت کنیم
مثلا همیشه تابعی که داره تست میشه result (یا actrual) برمیگردونه
var result = _sut.Execute(testData);

2024-08-03 09:28 UTC, AliSK81 commented on phase4/phase4/phase3Test/Processor/PreProcessor/ExtraSpaceRemoverTest.cs
> +    public void ExtraSpaceRemover_ShouldReturnNullReferenceException_WhenInputHaveNullFile()
ShouldThrow

2024-08-03 10:53 UTC, Ftm-Sayadzadeh approved these changes

2024-08-03 11:22 UTC, navidnasyry approved these changes
سعی کنین از این به بعد از کتابخونه‌های [Fluent Assertions](https://www.fluentassertions.com/)و [NSubstitute](https://nsubstitute.github.io/)

2024-08-03 11:35 UTC, merged